# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Qwen3-8B variant tests for MXFP8 matrix multiplication kernel.

Tests the Qwen3-8B model shapes under different input configurations:
pre-quantized, pre-swizzled, unswizzled BF16, and spill-reload.
"""

import numpy as np
import pytest

from nkilib_src.nkilib.experimental.matmul_mxfp8 import matmul_mxfp8_generic_kernel
from nkilib_src.nkilib.experimental.matmul_mxfp8.matmul_mxfp8_torch import matmul_mxfp8_torch_ref
from test.integration.nkilib.experimental.matmul_mxfp8 import (
    config_helper,
    constants,
    model_config_reader,
)
from test.integration.nkilib.experimental.matmul_mxfp8.test_matmul_mxfp8_generic_kernel import (
    _mxfp8_comparator,
    build_matmul_inputs,
    get_output_dtype,
)
from test.utils import common_dataclasses
from test.utils.pytest_test_metadata import pytest_test_metadata
from test.utils.unit_test_framework import UnitTestFramework


def populate_tests(grid, auto_generate_default=False):
    """Populate test configurations from a grid of base configs.

    When auto_generate_default is True, uses autoGenerateDefault() which
    produces a single deterministic configuration per grid entry.
    Otherwise falls back to autoGenerateRandomSubset().
    """
    res = []
    for conf in grid:
        if auto_generate_default:
            res += conf.autoGenerateDefault()
        else:
            res += conf.autoGenerateRandomSubset(3)
    return res


def _make_qwen_configs(run_with_lnc2=None, enable_scale_packing=True, **overrides):
    """Create Qwen3-8B configs with overrides applied BEFORE autoGenerateDefault.

    run_with_lnc2 defaults to None so autoGenerateDefault will try LNC2 first
    and fall back to LNC1 when the shape doesn't support it.
    """
    base_configs = model_config_reader.qwen3_8b_tp4
    configs = []
    for base in base_configs:
        conf = config_helper.TestConfig(
            M=base.M,
            K=base.K,
            N=base.N,
            description=base.description,
            run_with_lnc2=run_with_lnc2,
            enable_scale_packing=enable_scale_packing,
            **overrides,
        )
        configs.append(conf)
    return populate_tests(configs, auto_generate_default=True)


# Case 1: Pre-quantized (MXFP8) + swizzled + LNC2, no spill reload
GRID_PREQUANTIZED_SWIZZLED = _make_qwen_configs(
    lhs_dtype=constants.MatrixPrecision.MXFP8,
    rhs_dtype=constants.MatrixPrecision.MXFP8,
    lhs_is_swizzled=True,
    rhs_is_swizzled=True,
    spill_reload=False,
    enable_scale_packing=True,
)

# Case 2: Pre-swizzled, no scale packing, no spill reload
GRID_SWIZZLED_BF16_NO_SCALE_PACKING = _make_qwen_configs(
    lhs_dtype=constants.MatrixPrecision.BFLOAT16,
    rhs_dtype=constants.MatrixPrecision.BFLOAT16,
    lhs_is_swizzled=True,
    rhs_is_swizzled=True,
    spill_reload=False,
    enable_scale_packing=False,
)

# Case 3: Pre-swizzled, Enable scale packing, No spill reload
GRID_SWIZZLED_BF16_SCALE_PACKING = _make_qwen_configs(
    lhs_dtype=constants.MatrixPrecision.BFLOAT16,
    rhs_dtype=constants.MatrixPrecision.BFLOAT16,
    lhs_is_swizzled=True,
    rhs_is_swizzled=True,
    spill_reload=False,
    enable_scale_packing=True,
)

# Case 4: Pre-swizzled, No scale packing, Spill reload enabled
GRID_SWIZZLED_BF16_SPILL_RELOAD = _make_qwen_configs(
    lhs_dtype=constants.MatrixPrecision.BFLOAT16,
    rhs_dtype=constants.MatrixPrecision.BFLOAT16,
    lhs_is_swizzled=True,
    rhs_is_swizzled=True,
    spill_reload=True,
    enable_scale_packing=False,
)

# Case 5: Pre-swizzled, BOTH scale packing and spill reload
GRID_SWIZZLED_BF16_SCALE_PACKING_SPILL_RELOAD = _make_qwen_configs(
    lhs_dtype=constants.MatrixPrecision.BFLOAT16,
    rhs_dtype=constants.MatrixPrecision.BFLOAT16,
    lhs_is_swizzled=True,
    rhs_is_swizzled=True,
    spill_reload=True,
    enable_scale_packing=True,
)


# Case 6: Unswizzled BF16 (not quantized, not swizzled) + LNC2
def _make_unswizzled_bf16_configs():
    """Create unswizzled BF16 configs requiring tile_m=128, tile_k=512, TILES_IN_LOAD_M=4, TILES_IN_LOAD_N=1."""
    base_configs = model_config_reader.qwen3_8b_tp4
    configs = []
    for base in base_configs:
        # Unswizzled (DGT) requires tile_k=512; skip shapes where K < 512
        if base.K < 512:
            continue
        # tile_n=512 for DGT when N >= 512, otherwise tile_n=N
        tile_n = 512 if base.N >= 512 else base.N
        conf = config_helper.TestConfig(
            M=base.M,
            K=base.K,
            N=base.N,
            description=base.description,
            run_with_lnc2=None,
            enable_scale_packing=False,
            lhs_dtype=constants.MatrixPrecision.BFLOAT16,
            rhs_dtype=constants.MatrixPrecision.BFLOAT16,
            lhs_is_swizzled=False,
            rhs_is_swizzled=False,
            tile_m=128,
            tile_n=tile_n,
            tile_k=512,
            TILES_IN_LOAD_M=4,
            TILES_IN_LOAD_N=1,
            spill_reload=True,
        )
        configs.append(conf)
    return populate_tests(configs, auto_generate_default=True)


GRID_UNSWIZZLED_BF16 = _make_unswizzled_bf16_configs()


@pytest_test_metadata(
    name="Matmul MXFP8 Qwen3-8B Variants",
)
@pytest.mark.platforms(exclude=[common_dataclasses.Platforms.TRN1, common_dataclasses.Platforms.TRN2])
class TestMatmulMxfp8Qwen38bVariants:
    """Qwen3-8B model shape tests under different input configurations."""

    def _run_test(self, test_manager, conf, platform_target, gpu_golden_enabled=False):
        if not platform_target.is_trn3():
            pytest.skip("MX is only supported on TRN3.")

        compiler_args = common_dataclasses.CompilerArgs(
            logical_nc_config=2 if conf.run_with_lnc2 else 1,
            platform_target=platform_target,
            additional_cmd_args=["--internal-backend-options=--enable-mx-alternative-emax"],
        )

        test_manager.collector.set_kernel_params(conf.to_metrics_dict())
        output_dtype = get_output_dtype(conf)

        def input_generator(test_config):
            return build_matmul_inputs(conf)

        def output_tensors(kernel_input):
            return {"out": np.zeros((conf.M, conf.N), dtype=output_dtype)}

        framework = UnitTestFramework(
            test_manager=test_manager,
            kernel_entry=matmul_mxfp8_generic_kernel.matmul_mxfp8,
            torch_ref=matmul_mxfp8_torch_ref,
            kernel_input_generator=input_generator,
            output_tensor_descriptor=output_tensors,
        )
        framework.run_test(
            test_config=None,
            compiler_args=compiler_args,
            custom_comparator=_mxfp8_comparator(conf, output_dtype, gpu_golden_enabled),
        )

    @pytest.mark.parametrize("conf", GRID_PREQUANTIZED_SWIZZLED)
    def test_qwen3_8b_prequantized_swizzled(self, test_manager, conf, platform_target):
        """Case 1: Pre-quantized MXFP8 + swizzled, no spill reload."""
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_SWIZZLED_BF16_NO_SCALE_PACKING)
    def test_qwen3_8b_swizzled_bf16_no_scale_packing(self, test_manager, conf, platform_target):
        """Case 2: Pre-swizzled BF16, no scale packing, no spill reload."""
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_SWIZZLED_BF16_SCALE_PACKING)
    def test_qwen3_8b_swizzled_bf16_scale_packing(self, test_manager, conf, platform_target):
        """Case 3: Pre-swizzled BF16, scale packing enabled, no spill reload."""
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_SWIZZLED_BF16_SPILL_RELOAD)
    def test_qwen3_8b_swizzled_bf16_spill_reload(self, test_manager, conf, platform_target):
        """Case 4: Pre-swizzled BF16, no scale packing, spill reload enabled."""
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_SWIZZLED_BF16_SCALE_PACKING_SPILL_RELOAD)
    def test_qwen3_8b_swizzled_bf16_scale_packing_spill_reload(self, test_manager, conf, platform_target):
        """Case 5: Pre-swizzled BF16, BOTH scale packing and spill reload."""
        self._run_test(test_manager, conf, platform_target)

    @pytest.mark.parametrize("conf", GRID_UNSWIZZLED_BF16)
    def test_qwen3_8b_unswizzled_bf16(self, test_manager, conf, platform_target):
        """Case 6: Unswizzled BF16 (not quantized, not swizzled)."""
        self._run_test(test_manager, conf, platform_target)
